name: DART_SIDE
version: 1.0.0

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  postgres: ^3.1.0
  # path: ^1.8.0
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
